### ISSUE TITLE
Provide an option to use typed english word as it is as well

### ISSUE THREAD

**Issue by dhoomakethu** [ratreya/lipika-ime#30]
At present when the correct indic word is not provided by the keyboard, there is no option to use the typed in english word as it is. Provide an option to use the english word as it is as well.

For e.g

With google indic transliteration , I could see something like this and can use englishe 'installer' if not satisfied with any of the transliterated words.

![screen shot 2017-10-18 at 11 04 52](https://user-images.githubusercontent.com/9276974/31702376-4f97b7f2-b3f4-11e7-9906-1539ee1789d6.png)

With LipikaIME
![screen shot 2017-10-18 at 11 05 14](https://user-images.githubusercontent.com/9276974/31702380-5843567c-b3f4-11e7-83ce-176458bdf7aa.png)

**Comment by dhoomakethu** [comment]
Ok I found out a workaround, just to click on the typed in text to use as it is. But having it as part of the popup is preferable,  Please close this issue if you think that is not necessary.

**Comment by ratreya** [comment]
In v2, you can use escape characters (default is \`) to type in English. For example, \`test\` will output `test`. This will be available once v2 is released.

**Comment by ratreya** [comment]
Fixed in v2. Will be releasing soon.
