### ISSUE TITLE
Cannot input consecutive digits

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#32]
Devanagari/Barahavat. Repros on other scripts and other schemes as well.

I type in `<digit1><digit2><digit3>`.

Expected: `१२३`.
Actual: just `१`. The subsequent keystrokes do nothing, until I hit "Enter".

**Comment by ratreya** [comment]
I was able to easily repro the issue. However, a simple unit test at the Engine layer did not have this problem. Will dig more over the weekend.

**Comment by ratreya** [comment]
Fixed in v2. Will be releasing soon.
