### ISSUE TITLE
Sending HUP to the process should make it re-read config

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#33]
This is a feature-request. Could we have the LipikaIME process respond to SIGHUPs by re-reading its config? Developers wouldn't have to kill the process manually.

**Comment by ratreya** [comment]
This is a good idea - will squirrel this away for when I find time.

**Comment by ratreya** [comment]
With LipikaIME v2, any edits to the mapping using LipikaApp is immediately reflect in LipikaIME. Hence, closing as won't fix.
