### ISSUE TITLE
Please can you provide the transliteration scheme for 'jna' in Devnagari  

### ISSUE THREAD

**Issue by vidyanarayanan** [ratreya/lipika-ime#43]
In the transliteration scheme,  it would be great to add the samyuktaashara-scheme for jna as in jnaanam: https://github.com/ratreya/lipika-ime/wiki/Transliteration-Schemes 

I'd be happy to update it if you can let me know the scheme in this issue. Thanks!

**Comment by sriharshachilakapati** [comment]
జ్ఞానం - ज्ञानम् (j~jAnam) It's not jna but j~ja where you've to type the tilde symbol. This is the Baraha scheme that I'm using.

**Comment by vidyanarayanan** [comment]
Got it, thank you!  jJN or j~n ज्ञ् works in ITRANS that I use. I will close this.
