### ISSUE TITLE
Font is frequently automatically changing upon input

### ISSUE THREAD

**Issue by sriharshachilakapati** [ratreya/lipika-ime#44]
When I'm entering the input in Apple's Pages application, the font changes automatically even if the preceding text has the font set. It's automatically setting back to Helvetica, which is the default font in the preview panel.

![font_change](https://user-images.githubusercontent.com/4593204/49060807-0a03a680-f235-11e8-8a35-27e52b2d0090.gif)

However, in my case I've disabled the popups so this shouldn't happen anymore. What can I do in order to fix it?

I'm running this on a 2017 MacBook Air, running macOS Mojave 10.14.1

**Comment by ratreya** [comment]
Closing this as a bug in Pages. I tried in Word and could not repro the issue.

There is now a completely reworked [v2 beta release of LipikaIME](https://github.com/ratreya/lipika-ime/releases/tag/v2.1-beta) that you can try out. Even in the new release, as you can see [here](https://github.com/ratreya/lipika-ime/blob/1991b0f53baceec5fa310d4a96f8e4bc8f6415d2/Input%20Source/ClientManager.swift#L84), we only insert a non-attributed plain string.

But it would be interesting to see if the issue repros on the latest release. Please try it out.
