### ISSUE TITLE
v2.0-alpha.1 crashes with SIGILL on 10.14.2

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#45]
**Describe the bug**
I tried out the new v2.0-alpha.1 on my Mojave laptop, and could never get it to work. I installed it, and it crashed on first use. See below.

**To Reproduce**
1. Download https://github.com/ratreya/lipika-ime/releases/download/v2.0-alpha.1/LipikaIME.pkg
1. Run through installation.
1. Open Keyboard preferences and add LipikaIME.
1. Switch to LipikaIME from the system tray.
1. Switch focus to Chrome window and start typing.

**Expected behaviour**
Devanagari output.

**Actual behaviour**
Latin output. And Lipika seems to have crashed. See screenshot below. The following's from system.log
`Jan 26 23:28:01 steel com.apple.xpc.launchd[1] (com.daivajnanam.inputmethod.LipikaIME.15900[4259]): Service exited due to SIGILL | sent by exc handler[4259]`

**Screenshots**
<img width="246" alt="screenshot 2019-01-26 at 23 34 19" src="https://user-images.githubusercontent.com/5531915/51798164-28e5d100-21c3-11e9-80ff-01cf83c29735.png">

**Desktop:**
 - OS: OSX 10.14.2 (18C54)
 - Browser: Chrome 71.0.3578.98

**Comment by ratreya** [comment]
Fixed. For future reference assert() takes an automatic closure that does not execute in production! Please download the alpha release pkg again and reinstall.

**Comment by deepestblue** [comment]
Verified fixed. Thanks!
