### ISSUE TITLE
v1.7.4. Commit text on "Enter": behaviour change with Mojave?

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#46]
**Describe the bug**
Lipika 1.7.4. I upgraded to Mojave, and see what seems to be a change in behaviour. On Mojave, hitting Enter no longer seems to commit what's in the pop-up. Only space or switching to a different input source seem to work. 

**To Reproduce**
1. Install Lipika 1.7.4.
1. Select to Devanagari/Ksharanam.
1. Switch to Chrome's URL bar.
1. Type the keys `m` `a` `m` `a` `Enter`, in that order.

**Expected behaviour and actual behaviour on 10.13.6 (17G4015)**
`मम` in the URL bar.

**Actual behaviour on 10.14.2 (18C54)**
`मम` in the popup window. Not committed.

**Screenshots**
<img width="296" alt="screenshot 2019-01-26 at 23 53 47" src="https://user-images.githubusercontent.com/5531915/51798370-ac082680-21c5-11e9-8005-9ef0a17002df.png">

<img width="251" alt="screenshot 2019-01-26 at 23 54 38" src="https://user-images.githubusercontent.com/5531915/51798377-cd691280-21c5-11e9-930c-8f456ab026b5.png">

**Desktop (please complete the following information):**
 - OS: 10.14.2 (18C54)
 - Browser: Chrome 71.0.3578.98

**Comment by ratreya** [comment]
Can you please test using the latest 2.0 alpha release and report back? I am stopping support for older versions and hoping to save myself from looking at Objective C ever again.

**Comment by ratreya** [comment]
Fixed in v2.0.
