### ISSUE TITLE
Crash when switching scripts when in Chrome

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#48]
**Attach the crash report**
[LipikaIME_2019-03-09_steel.crash.zip](https://github.com/ratreya/lipika-ime/files/2949045/LipikaIME_2019-03-09_steel.crash.zip)

**What I was doing (not sure if reproducible)**
1. Launch LipikaIME
2. Select Ksharanam Scheme and ISO-15919 Script
3. Start typing in Chrome
4. Try switching to Tamil
5. Notice output remains in ISO-15919
6. Go to Console and notice the crash report

**Desktop (please complete the following information):**
 - macOS 10.14.3
 - Application: Chrome 72.0.3626.12
 - Version: v2.0-alpha.1

**Comment by ratreya** [comment]
Fixed by 0c804a8d4f9bfb0bd125df1a96b2a001df60bcd3. Will be in the next beta release.
