### ISSUE TITLE
SIGSEGV 

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#49]
**Attach the crash report**
[LipikaIME_2019-03-10-134635_steel.crash.txt](https://github.com/ratreya/lipika-ime/files/2950046/LipikaIME_2019-03-10-134635_steel.crash.txt)

**To Reproduce**
Not sure exactly what I was doing, but I did a killAll LipikaIME to make it re-read some changes in the Mappings. And then I tried switching to it from the menu-bar.

**Desktop (please complete the following information):**
 - OS: macOS 10.14.3
 - Version: 2.0-alpha.1

**Additional context**
I have a change in one of the Override files. Could that be the cause?

**Comment by deepestblue** [comment]
Attaching more crash files.
[SIGSEGVs.zip](https://github.com/ratreya/lipika-ime/files/2950887/SIGSEGVs.zip)

**Comment by ratreya** [comment]
I finally debugged and fixed this entire class of crashes in 0c804a8d4f9bfb0bd125df1a96b2a001df60bcd3. I will cut a beta release with the fix soon.
