### ISSUE TITLE
Keyboard shortcut for switching scripts

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#52]
**Is your feature request related to a problem? Please describe.**
I use LipikaIME for multiple scripts (Tamil, Grantha, ISO-15919, etc.), and switch scripts often mid-sentence, especially when writing in Manipravalam.

**Describe the solution you'd like**
Would love a keyboard shortcut to switch scripts.

**Comment by ratreya** [comment]
This feature is available in the latest pre-release. Please try it out: https://github.com/ratreya/lipika-ime/releases/tag/2.2

**Comment by ratreya** [comment]
Available in v2.2 now in GA.

**Comment by deepestblue** [comment]
Works well, thanks!
