### ISSUE TITLE
Use in login screen

### ISSUE THREAD

**Issue by adarshvadwitiya** [ratreya/lipika-ime#53]
**Is your feature request related to a problem? Please describe.*t
I cannot use this on the login or lock screen despite enabling the `Show Input menu in login window` option in `Login Options`. I don't know if this is a problem that can be addressed but it would be really helpful. I would like to keep an Indian language login password

**Describe the solution you'd like**
Currently, I see the default Keyboard selected and a list of other languages but I do not see **LipikaIME** in the list. Would be great if LipikaIME is shown in the list

**Describe alternatives you've considered**
None

**Additional context**
I would like to see **LipikaIME** in this menu:
<img width="830" alt="Screen Shot 2019-11-21 at 6 05 57 PM" src="https://user-images.githubusercontent.com/30106062/69338659-ac5c3b80-0c89-11ea-91c1-d91b894b9176.png">

**Comment by ratreya** [comment]
I did some research and unfortunately, it does not look like Mac OS supports third party IMEs on the login screen. Understandably, it could be a security risk since the IME will have access to the characters of the password. Closing as `wontfix`.

**Comment by adarshvadwitiya** [comment]
@ratreya I understand. Thanks for investigating
