### ISSUE TITLE
Installation of latest package does not complete on High Sierra

### ISSUE THREAD

**Issue by shivahnshankar** [ratreya/lipika-ime#54]
**Describe the bug**
During the installation, the install process seems to hang on "Running package scripts". The package is available in the Applications folder and can be added to the keyboard layout though.

**To Reproduce**
1. Just try to install on High Sierra Macos

**Expected behavior**
Installation to be completed fully

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Application: None
 - Version: Latest version

**Comment by shivahnshankar** [comment]
Version 2.1

**Comment by vassadi** [comment]
I was trying to install the same on Mac Catalina, it was saying **Apple can not check for malicious software**.

**Comment by meghanae** [comment]
Faced the same issue on Sierra. The package installation didn't complete. But the app was installed. Later had to force shut down the system to quit the installation process.

**Comment by manoharnikkam** [comment]
Faced same issue on Catalina. I get "LipikalME.pkg can't be opened because Apple cannot check it for malicious software."

![image](https://user-images.githubusercontent.com/8573069/79017374-c2826f80-7b36-11ea-9ead-570aa89a60cc.png)

**Comment by yashodhank** [comment]
@manoharnikkam if you right click on file and then click open from menu option, it you will be able to run this file without any issue.
This is standard security mechanism with MacOS where downloaded application packages does not run with just one click, unless you override it.

**Comment by manoharnikkam** [comment]
Thank you very much @yashodhank. It worked. Appreciate it.

**Comment by mtikekar** [comment]
@shivahnshankar Looking through the install log, I realized that the installer cannot find Swift libraries. You can install them from https://support.apple.com/kb/DL1998?locale=en_GB. It will install them to `/usr/lib/swift` so you can check if you don't have them.

According to the Apple link, this extra step is only needed on macOS version 10.14.3 and earlier. They come pre-installed on newer versions. @ratreya please consider adding these to the install instructions.

**Comment by ratreya** [comment]
That's good sleuthing. I am inclined to up the minimum requirement to 10.14.4. The installer will refuse to install on an older OS version. Thanks for the investigation!

**Comment by mtikekar** [comment]
It does work nicely on older versions once you install the Swift libraries. And LipikaAPP works even without the Swift libraries because they are being packaged up into the app. Perhaps there is a way for the installer to link to those instead of `/usr/lib/swift`.

**Comment by ratreya** [comment]
I considered the option of hacking the search path to link against the libraries in the App. However, the next version that is currently being worked on in trunk uses SwiftUI which anyway requires 10.15. So, it renders the library issue moot.

**Comment by ratreya** [comment]
The latest release has a minimum requirement of 10.15 which is required for SwiftUI. Closing this as wontfix.
