### ISSUE TITLE
Strange disappearing characters in GMail

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#56]
**Describe the bug**
When composing in GMail, under specific circumstances, characters seem to get inputted but then disappear immediately. Repros in rare circumstances, but deterministically.

**To Reproduce**
1. Start composing email in GMail. [I tried both inline and modal].
2. Switch to LipikaIME, Devanagari, ITRANS. [Also repros on Ksharanam].
3. Type in `tAvate upayogAya na` to try to input `तावते उपयोगाय न`.
4. Notice the `न` disappears.

**Screenshots**
This shows me trying to type `न` four times, and it disappearing four times.

![Screen Recording 2020-07-24 at 14 13 38](https://user-images.githubusercontent.com/5531915/88436718-ba82ce80-cdb9-11ea-87d7-e75ba833e46c.gif)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.6
 - Application: Chrome
 - Version: 84.0.4147.89 

**Additional context**
I remember seeing this in 2.1 as well but only finally got a consistent repro in 2.2, so this isn't a regression in 2.2.

**Comment by ratreya** [comment]
This has happened to me as well. It is gmail trying to be too smart for its own good. If you go into Settings -> General and turn off Grammar suggestions, Spelling suggestions and Autocorrect, such surprises can be avoided. I just tested A/B and confirmed that the fix would work.

**Comment by deepestblue** [comment]
You're right. Specifically, it was Spelling suggestions that was the culprit. I was able to retain Autocorrect and Grammar suggestions and still workaround this specific issue. Thanks!
