### ISSUE TITLE
Deergha Swaritam

### ISSUE THREAD

**Issue by ramadugu** [ratreya/lipika-ime#58]
How do you enable deergha swaritha for Vedic swaras?
Thank you!

Sai

**Comment by ratreya** [comment]
You can edit the mappings using LipikaApp - many people don't know about this partner app.
![Screen Shot 2020-12-14 at 12 20 57 PM](https://user-images.githubusercontent.com/3529167/102131906-c114ef80-3e07-11eb-85da-1067e4c50d23.png)

**Comment by ramadugu** [comment]
Still not working with " or '' and 951, 951 for script. Only Swarita shows up. Sorry if this really a noob/dumb thing from my side.
<img width="680" alt="CleanShot 2020-12-14 at 15 01 21@2x" src="https://user-images.githubusercontent.com/12400630/102135227-48209280-3e1d-11eb-9849-76030e00f5dd.png">

**Comment by ratreya** [comment]
I believe this is a font rendering issue. In fact, you don't need any special mappings. If you use Siddhanta font and type udatta twice, it will render it as deergha.

**Comment by ratreya** [comment]
[Unicode standard for Devanagari](https://unicode.org/charts/PDF/U0900.pdf) does not specify a deergha udatta/swarita character.  Some fonts like Siddhaanta take two udaattas and make it deergha. As such, this is more a font issue than an IME issue. Closing as wontfix.

**Comment by ramadugu** [comment]
Hi Ranganath,

I thought I would update you on the Telugu font that has the Vedic accents reproduce correctly, Lohit set of fonts work the best,

https://www.fontsc.com/font/designer/lohit-fonts-project <https://www.fontsc.com/font/designer/lohit-fonts-project>

I have one question though:

How can one change the font that Lipika IME uses, I mean in the companion app that comes with Lipika.

Best,
Sai

**Comment by ratreya** [comment]
Thanks for the font pointers. Can you please post in [LipikaIME User Group](https://www.facebook.com/groups/lipika.ime) so others with the same problem will find the answer?
There is no way to change the font in LipikaApp at this point. But as long as you get the unicode hex code correctly entered with comma separation, it should just work.
