### ISSUE TITLE
Needs update for macOS Big Sur

### ISSUE THREAD

**Issue by ezoerner** [ratreya/lipika-ime#59]
I'd love to use this on my Mac with macOS 11.1 (Big Sur) but when trying to run the installer I get an error as shown in the attached screenshot.
<img width="259" alt="Screen Shot 2021-01-13 at 20 16 58" src="https://user-images.githubusercontent.com/1067835/104544477-ae473380-55dc-11eb-9be2-6b0b9c651b27.png">

**Comment by ratreya** [comment]
This release *should* work for the latest macos versions: https://github.com/ratreya/lipika-ime/releases/tag/v2.2.1.
