### ISSUE TITLE
Lipika Ime - Not compatible with Mac OS Big Sur

### ISSUE THREAD

**Issue by vasubv** [ratreya/lipika-ime#60]
Hello Lipika Ime is not compatible with the latest Mac OS - Mac OS Big Sur. Please make this compatible. This software is the heart of many indian languages. I absolutley love it. @ratreya - My humble request that you should consider making this compatible with the latest Mac OS. thanks a ton

Vasudevan

**Comment by ratreya** [comment]
Apple, the greedy monopoly, is trying to force all Apps into the AppStore by making life outside AppStore miserable. I would happily move LipikaIME into the AppStore if they supported IMEs which they don't.

I will look into this and fix once I update to Big Sur. In the meantime, you can bypass this right-clicking on installer and choosing open from the context menu.

**Comment by vasubv** [comment]
Hello @ratreya - I do agree Apple is lousy. They are very greedy. Why will they not offer backward compatibility to great apps like Lipika ime

Also @ratreya, Can you please provide an update on where we stand. For this reason I have not upgraded my mac book from my Mac OS Catalina to Mac Sur OS. I fear after the upgrade Lipika ime may not work. 

Wanted to understand better when you say there is a workaround, by rightclicking on the installer and choosing open from the context menu. Please highlight what exactly you mean. In this approach will I be able to work with Lipika time, if i upgrade to Mac OS Big Sur? many thanks for your help as always !

best regards 
Vasudevan

**Comment by ratreya** [comment]
This release *should* work for the latest macos versions: https://github.com/ratreya/lipika-ime/releases/tag/v2.2.1. BTW, if you do update your OS, you don't need to reinstall LipikaIME. For me, it just continued working.

**Comment by vasubv** [comment]
Thanks Atreya. You are great ! Your softwareis a boon to Indian languages. May you continue your earnest efforts in keeping this packagae live and kicking with generations to come. God bless you

**Comment by vasubv** [comment]
If possible pleaseshare ur email/phone number so i keep them handy. My email is vasubv@gmail.com. Im reachabe at 504-908-6168

**Comment by ratreya** [comment]
Thanks for your kind words. I am glad the software is helping support Indic languages.

**Comment by vasubv** [comment]
Hi @ratreya - sorry for troubling you again. Is the Lipika software compatible with Ventura latest Apple is? I’m still on Mac Sur for the fear of losing this lovely software please advise 🙏

**Comment by ratreya** [comment]
I recently upgraded to Ventura and can confirm that LipikaIME continued to work as expected through the upgrade.

**Comment by vasubv** [comment]
Thanks @ratreya will try upgrading it today. BTWdo you have WhatsApp number I can reach out ? Can you please share would like to talk to you my number is 716-352-3254
