### ISSUE TITLE
No such module 'LipikaEngine_OSX'

### ISSUE THREAD

**Issue by sspogra1** [ratreya/lipika-ime#62]
Getting error 'No such module 'LipikaEngine_OSX' while  compile from xcode. See attached image.
<img width="1121" alt="Screenshot at May 22 22-32-54" src="https://user-images.githubusercontent.com/84637174/119234917-b47e8b00-bb4d-11eb-9fc4-97fc0cf908f2.png">

**Comment by ratreya** [comment]
git clone [lipika-engine](https://github.com/ratreya/lipika-engine) and [shortcut recorder](https://github.com/Kentzo/ShortcutRecorder) repos into sibling directories of lipika-ime and run lipika-ime/Installation/build. It will build and copy the dependencies into the right folders.

**Comment by subins2000** [comment]
I'm having the same problem. Can you please clearly document how to get a build of LipikaIME locally please ? The contributing page doesn't mention any of it https://github.com/ratreya/lipika-ime/blob/master/.github/CONTRIBUTING.md

I can see that ShortcutRecorder is added in `.gitmodules` but not the engine
