### ISSUE TITLE
Lipika is not showing Harvard-Kyoto as input

### ISSUE THREAD

**Issue by uditadas** [ratreya/lipika-ime#63]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.14.3]
 - Application: [e.g. textedit, safari]
 - Version: [e.g. 2.2]

**Smartphone (please complete the following information):**
 - Application: [e.g. whatsapp, imessage]
 - Version: [e.g. 2.1]

**Additional context**

**Comment by ratreya** [comment]
Can you please fill-in the template that was populated in the description. Just the title does not give me enough information to root-cause your issue, which BTW is very likely user error.

**Comment by uditadas** [comment]
Sorry! I had to restart the computer to make it work. Thank you for your help. 

Best,
Udita
