### ISSUE TITLE
Difficulty

### ISSUE THREAD

**Issue by Maniiiiyer** [ratreya/lipika-ime#69]
**Describe the bug**
A clear and concise description of the bug.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. macOS 10.14.3]
 - Application: [e.g. textedit, safari]
 - Version: [e.g. 2.2]

**Smartphone (please complete the following information):**
 - Application: [e.g. whatsapp, imessage]
 - Version: [e.g. 2.1]

**Additional context**

**Comment by Maniiiiyer** [comment]
How to type the following
ङ ञ ज्ञ and ऽ ? Could someone please help ?

**Comment by ratreya** [comment]
Please post this in the [user group](http://facebook.com/groups/lipika.ime) or [discussion forums](https://github.com/ratreya/lipika-ime/discussions).
