### ISSUE TITLE
LipikaIME stopped working on upgrade to Ventura

### ISSUE THREAD

**Issue by deepestblue** [ratreya/lipika-ime#71]
**Describe the bug**
I upgraded to Ventura from Big Sur, and next time I switched to Lipika, I got an error message that "Lipika IME is damaged". I uninstalled and reinstalled, and now when I try to switch to it I don't see it anymore.

**To Reproduce**
1. Upgrade to Ventura
2. Install latest release of LipikaIME
3. Try to switch to it
4. Nothing happens

**Expected behavior**
Able to use LipikaIME

**Desktop (please complete the following information):**
 - OS: macOS 13.0
 - Application: Any
 - Version: 2.2.1

**Additional context**
I don't know if the revamp of the settings page means I'm configuring it wrong.

**Comment by subins2000** [comment]
Does this happen still when you reinstall Lipika ?

**Comment by deepestblue** [comment]
> I uninstalled and reinstalled, and now when I try to switch to it I don't see it anymore.

**Comment by ratreya** [comment]
I am updating to Ventura today - hope to debug this soon.

**Comment by ratreya** [comment]
LipikaIME is working fine after the update for me. Can you please go to LipikaApp->Settings and set logging to Debug. Restart your computer, switch to LipikaIME and send me relevant logs from Console app?

**Comment by deepestblue** [comment]
And ... soon as I did that, and restarted, it stopped reproing 🤦

Will close this one out and reopen if it happens again. Thanks!
